# Generated by Django 4.2.5 on 2024-03-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('social_security_number', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('surname', models.TextField(blank=True, null=True)),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('health_insurance_number', models.TextField(blank=True, null=True)),
                ('date_enrolled', models.TextField(blank=True, null=True)),
                ('registered_by', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('patient_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.BigIntegerField()),
                ('medical_condition', models.TextField(blank=True, null=True)),
                ('clinical_notes', models.TextField(blank=True, null=True)),
                ('date_of_consultation', models.TextField(blank=True, null=True)),
                ('staff_id', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('designation', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('password', models.TextField()),
                ('date_registered', models.TextField(blank=True, null=True)),
                ('otp', models.TextField(blank=True, null=True)),
                ('otp_expiration', models.TextField(blank=True, null=True)),
                ('authentication_token', models.TextField(blank=True, null=True)),
                ('verified', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('designation', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('password', models.TextField()),
                ('date_registered', models.TextField(blank=True, null=True)),
                ('otp', models.TextField(blank=True, null=True)),
                ('otp_expiration', models.TextField(blank=True, null=True)),
                ('authentication_token', models.TextField(blank=True, null=True)),
                ('verified', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
